module.exports = {
  "ALIVE_IMG": "",
  "FOOT": "© CyberPsycho",
  "PREFIX": ".",
  "AUTO_READ_STATUS": "true",
  "MODE": "private",
  "BOT_NUMBER": "51978195933",
  "OMDB_API_KEY": "76cb7f39",
  "READ_CMD": "false",
  "AUTO_VOICE": "false",
  "ANTI_BAD": "warn",
  "ANTI_BOT": "true",
  "ANTI_CALL": "true",
  "ANTI_LINK": "true",
  "ANTI_PHOTO": "warn",
  "ANTI_STICKER": "warn",
  "ANTI_DELETE": true,
  "DELETEMSGSENDTO": "51978194933",
  "ALWAYS_ONLINE": "true",
  "MOROCCO_BLOCK": "true",
  "OWNER_NAME": "© SysSolutions",
  "OWNER_NUMBER": "51978194933",
  "AUTO_BIO": "true",
  "AUTO_TYPING": "false",
  "AUTO_RECORDING": "true",
  "WARN_COUNT": "3",
};
